# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "nvme" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/88b45b02-0a7e-4dc3-9cdb-27660f897380";
    fsType = "btrfs";
    options = [ "subvol=root" "compress=zstd" ];
  };

  boot.initrd.luks.devices."system".device =
    "/dev/disk/by-uuid/e048eb9c-a38e-4473-99f0-b15e55e455ab";

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/88b45b02-0a7e-4dc3-9cdb-27660f897380";
    fsType = "btrfs";
    options = [ "subvol=home" "compress=zstd" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/88b45b02-0a7e-4dc3-9cdb-27660f897380";
    fsType = "btrfs";
    options = [ "subvol=nix" "compress=zstd" "noatime" ];
  };

  fileSystems."/.snapshots" = {
    device = "/dev/disk/by-uuid/88b45b02-0a7e-4dc3-9cdb-27660f897380";
    fsType = "btrfs";
    options = [ "subvol=snapshots" "noatime" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/AC94-CC40";
    fsType = "vfat";
  };

  swapDevices = [{
    device = "/dev/disk/by-partuuid/49a76016-7ff6-4642-9a02-3f286f052473";
    randomEncryption.enable = true;
  }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
