{
  replacement = [
    "Name1"
    "Name2"
    "Username1"
    "example@email.com"
    "example2@email.com"
    "example3@email.com"
    "example@hotmail.com"
    "example@gmail.com"
    "Username2"
    "Jane Doe"
    "John Doe"
    "Bob Doe"
    "jane doe"
    "john doe"
    "bob doe"
    "orga1-short"
    "Orga2"
    "orga2"
    "orga2-short"
    "orga3"
    "Orga3"
    "Orga1"
    "Orga4"
    "orga4"
    "404-repo"
  ];
}
