#!/bin/sh
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-fill $SCRIPTPATH/down.jpg
fi

leftwm command "UnloadTheme"

pkill picom
pkill polybar
pkill dunst
pkill nm-applet
