#!/bin/sh
export SCRIPTPATH
SCRIPTPATH="$(
	cd "$(dirname "$0")" || exit
	pwd -P
)"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
	/tmp/leftwm-theme-down
	rm /tmp/leftwm-theme-down
fi
ln -s "$SCRIPTPATH"/down /tmp/leftwm-theme-down

# Set the theme.toml config
leftwm command "LoadTheme $SCRIPTPATH/theme.toml"

# notifications
if [ -x "$(command -v dunst)" ]; then
	pkill dunst
	dunst -config $HOME/.config/leftwm/themes/current/conf/dunst.config &
fi

# picom (if it exists)
if [ -x "$(command -v picom)" ]; then
	picom --config $HOME/.config/leftwm/themes/current/conf/picom.config &>/dev/null &
fi

# nm-applet
if [ -x "$(command -v nm-applet)" ]; then
	nm-applet &
fi

# Screenshots with Flameshot
if [ -x "$(command -v flameshot)" ]; then
	flameshot &
fi
# [ WALLPAPERS ] #############################################################
# - Comment/uncomment the option you prefer

# 1) START - set random wallpapers -----------------------------------------+
if [ -x "$(command -v feh)" ]; then
	feh --randomize --bg-fill $HOME/Pictures/wallpapers/*
fi
# END ----------------------------------------------------------------------+

# 2) START - set ONE wallpaper for all displays ----------------------------+
#if [ -x "$(command -v feh)" ]; then
#  feh --bg-fill "$SCRIPTPATH"/wallpapers/atlas-ark-gruvbox-simple-lines.png
#fi
# END ----------------------------------------------------------------------+

# 3) START - set MULTIPLE wallpapers for all displays ----------------------+
# NOTE: the last image path DO NOT end with "\"
#if [ -x "$(command -v feh)" ]; then
#  feh --bg-fill \
#  "$SCRIPTPATH"/wallpapers/blue_unicat.png \
#  "$SCRIPTPATH"/wallpapers/pink_unicat.png
#fi
# END ----------------------------------------------------------------------+
##############################################################################

index=0
leftwm-state -q -n -t "$SCRIPTPATH"/sizes.liquid | sed -r '/^\s*$/d' | while read -r width; do
	barname="mainbar$index"
	monitor="$(polybar -m | awk -v i="$((index + 1))" 'NR==i{print}' | sed s/:.*// | tr -d '\n')"
	monitor=$monitor width=$((width - 16)) polybar -c "$SCRIPTPATH"/polybar.config $barname &
	index=$((index + 1))
done
